FROM golang:alpine as builder

RUN mkdir /build
WORKDIR /build

COPY go.mod .
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

# COPY the source code as the last step
COPY . .

# Build the binary
RUN CGO_ENABLED=0 go build -o envoy-xds-server ./cmd/xds/main.go

# Copy into scratch
FROM ubuntu
COPY --from=builder /build/envoy-xds-server /bin/envoy-xds-server
CMD ["/bin/envoy-xds-server"]
